FROM php:8.4-fpm

# Munkakönyvtár
WORKDIR /var/www/html

# Szükséges csomagok
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    libzip-dev \
    && docker-php-ext-install pdo pdo_mysql zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*