services:

  nginx:
    image: nginx:alpine
    container_name: pizzaparty-nginx

    ports:
      - "${HTTP_PORT}:80"

    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: pizzaparty-php

    volumes:
      - ./:/var/www/html

    environment:
      TZ: ${TZ}
      ORGANIZER_PASSWORD_HASH: ${ORGANIZER_PASSWORD_HASH}

    depends_on:
      - mysql

    restart: unless-stopped

  mysql:
    image: mysql:8.4

    container_name: pizzaparty-mysql

    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_hungarian_ci

    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest

    container_name: pizzaparty-phpmyadmin

    depends_on:
      - mysql

    ports:
      - "${PHPMYADMIN_PORT}:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M

    restart: unless-stopped

volumes:
  mysql_data: